// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7sIcCmSJf6XxkTQYcWOeIJUIKCXD7Dns',
    appId: '1:41445782814:web:3107e8768387e1f492450f',
    messagingSenderId: '41445782814',
    projectId: 'corvitweek2023',
    authDomain: 'corvitweek2023.firebaseapp.com',
    databaseURL: 'https://corvitweek2023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvitweek2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqH9KF4467Wn-M1FRyBc_-hWA3hVSvR4Y',
    appId: '1:41445782814:android:27ede23189fb47b392450f',
    messagingSenderId: '41445782814',
    projectId: 'corvitweek2023',
    databaseURL: 'https://corvitweek2023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvitweek2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5jHw2Wlg-2VBSP34afOaczx7dm2W-Kk8',
    appId: '1:41445782814:ios:e10ebe27a338b26892450f',
    messagingSenderId: '41445782814',
    projectId: 'corvitweek2023',
    databaseURL: 'https://corvitweek2023-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'corvitweek2023.appspot.com',
    iosBundleId: 'com.asfand.corvit.corvitWeekEve',
  );
}
